"""add finalizada ao thread_openai

Revision ID: 1a3e8b1d6114
Revises: 8a63ad88021f
Create Date: 2024-11-29 20:49:52.213602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3e8b1d6114'
down_revision = '8a63ad88021f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_openai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizada', sa.Boolean(), nullable=False, server_default=sa.sql.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_openai', schema=None) as batch_op:
        batch_op.drop_column('finalizada')

    # ### end Alembic commands ###
