"""empty message

Revision ID: 8a63ad88021f
Revises: 9ce488173da2
Create Date: 2024-11-27 10:19:06.001137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a63ad88021f'
down_revision = '9ce488173da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('disciplina',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('thread_openai', schema=None) as batch_op:
        batch_op.alter_column('tema',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_openai', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('tema',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.alter_column('serie',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('disciplina',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
