"""add open thread

Revision ID: 9ce488173da2
Revises: da58b187fdb9
Create Date: 2024-11-26 09:16:27.090627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce488173da2'
down_revision = 'da58b187fdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_openai',
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_openai', sa.String(length=128), nullable=False),
    sa.Column('tema', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.String(length=128), nullable=False),
    sa.Column('timestamp_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('timestamp_ultima_interacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_openai')
    # ### end Alembic commands ###
