"""add avaliacao_nota

Revision ID: cc74f421389a
Revises: 1a3e8b1d6114
Create Date: 2024-12-11 19:04:01.472808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc74f421389a'
down_revision = '1a3e8b1d6114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_openai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avaliacao_nota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_openai', schema=None) as batch_op:
        batch_op.drop_column('avaliacao_nota')

    # ### end Alembic commands ###
